#!/usr/bin/env ruby
require "thor"
require "mail"

class Jarvis < Thor
  desc "quickmail", "sends mail."
  def quickmail
    puts "quickmail in tha house ..."

    sendmail_running = false
    sendmail_running = true unless `ps aux | grep sendmai[l]`.blank?
    puts "sendmail running: #{sendmail_running}"
    return unless sendmail_running

    Mail.deliver do
      from    "jarvis@impossiblecreature.com"
      to      "travis@drillingx.com"
      subject  "jarvis is the bomb.com"
      body     "this is quickmail. i have no data."
      # add_file '/full/path/to/somefile.png'
    end

    puts "quickmail sent."
  end
end

Jarvis.start
